# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UN{civil scientific}
email: uncivunsci@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  UN{civil-scientific}. Get in touch: uncivunsci@protonmail.com; IG: UNcivUNsci; TikTok: UNcivUNsci.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: uncivunsci
github_username:  uncivunsci

permalink: /:title.html


# Build settings
markdown: kramdown
